//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSSnackbarPlugin\src\main\java\com\ashera\snackbar\SnackbarContentLayoutImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_SnackbarContentLayoutImpl")
#ifdef RESTRICT_SnackbarContentLayoutImpl
#define INCLUDE_ALL_SnackbarContentLayoutImpl 0
#else
#define INCLUDE_ALL_SnackbarContentLayoutImpl 1
#endif
#undef RESTRICT_SnackbarContentLayoutImpl

#if !defined (ASSnackbarContentLayoutImpl_) && (INCLUDE_ALL_SnackbarContentLayoutImpl || defined(INCLUDE_ASSnackbarContentLayoutImpl))
#define ASSnackbarContentLayoutImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASWidgetAttribute;
@class IOSClass;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASSnackbarContentLayoutImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (IOSClass *)getViewClass;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (jboolean)removeWithInt:(jint)index;

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASSnackbarContentLayoutImpl)

inline NSString *ASSnackbarContentLayoutImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASSnackbarContentLayoutImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASSnackbarContentLayoutImpl, LOCAL_NAME, NSString *)

inline NSString *ASSnackbarContentLayoutImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASSnackbarContentLayoutImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASSnackbarContentLayoutImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASSnackbarContentLayoutImpl_init(ASSnackbarContentLayoutImpl *self);

FOUNDATION_EXPORT ASSnackbarContentLayoutImpl *new_ASSnackbarContentLayoutImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSnackbarContentLayoutImpl *create_ASSnackbarContentLayoutImpl_init(void);

FOUNDATION_EXPORT void ASSnackbarContentLayoutImpl_initWithNSString_(ASSnackbarContentLayoutImpl *self, NSString *localname);

FOUNDATION_EXPORT ASSnackbarContentLayoutImpl *new_ASSnackbarContentLayoutImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSnackbarContentLayoutImpl *create_ASSnackbarContentLayoutImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASSnackbarContentLayoutImpl_initWithNSString_withNSString_(ASSnackbarContentLayoutImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASSnackbarContentLayoutImpl *new_ASSnackbarContentLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSnackbarContentLayoutImpl *create_ASSnackbarContentLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASSnackbarContentLayoutImpl)

@compatibility_alias ComAsheraSnackbarSnackbarContentLayoutImpl ASSnackbarContentLayoutImpl;

#endif

#if !defined (ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt_) && (INCLUDE_ALL_SnackbarContentLayoutImpl || defined(INCLUDE_ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt))
#define ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt_

#define RESTRICT_SnackbarContentLayout 1
#define INCLUDE_ADXSnackbarContentLayout 1
#include "SnackbarContentLayout.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASSnackbarContentLayoutImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt : ADXSnackbarContentLayout < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASSnackbarContentLayoutImpl:(ASSnackbarContentLayoutImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (jint)getMaxHeight;

- (jint)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(jint)height;

- (void)setMaxWidthWithInt:(jint)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt)

FOUNDATION_EXPORT void ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt_initWithASSnackbarContentLayoutImpl_(ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt *self, ASSnackbarContentLayoutImpl *outer$);

FOUNDATION_EXPORT ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt *new_ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt_initWithASSnackbarContentLayoutImpl_(ASSnackbarContentLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt *create_ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt_initWithASSnackbarContentLayoutImpl_(ASSnackbarContentLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt)

#endif

#pragma pop_macro("INCLUDE_ALL_SnackbarContentLayoutImpl")
