//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSSnackbarPlugin\src\main\java\com\ashera\snackbar\SnackbarPlugin.java
//

#include "J2ObjC_source.h"
#include "SnackbarContentLayoutImpl.h"
#include "SnackbarImpl.h"
#include "SnackbarLayoutImpl.h"
#include "SnackbarPlugin.h"
#include "WidgetFactory.h"


@implementation ASSnackbarPlugin

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASSnackbarPlugin_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (void)initPlugin {
  ASSnackbarPlugin_initPlugin();
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x9, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initPlugin);
  #pragma clang diagnostic pop
  static const J2ObjcClassInfo _ASSnackbarPlugin = { "SnackbarPlugin", "com.ashera.snackbar", NULL, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_ASSnackbarPlugin;
}

@end

void ASSnackbarPlugin_init(ASSnackbarPlugin *self) {
  NSObject_init(self);
}

ASSnackbarPlugin *new_ASSnackbarPlugin_init() {
  J2OBJC_NEW_IMPL(ASSnackbarPlugin, init)
}

ASSnackbarPlugin *create_ASSnackbarPlugin_init() {
  J2OBJC_CREATE_IMPL(ASSnackbarPlugin, init)
}

void ASSnackbarPlugin_initPlugin() {
  ASSnackbarPlugin_initialize();
  ASWidgetFactory_register__WithASIWidget_(new_ASSnackbarImpl_init());
  ASWidgetFactory_register__WithASIWidget_(new_ASSnackbarContentLayoutImpl_init());
  ASWidgetFactory_register__WithASIWidget_(new_ASSnackbarLayoutImpl_init());
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASSnackbarPlugin)
