//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSSnackbarPlugin\src\main\java\com\ashera\snackbar\SnackbarContentLayoutImpl.java
//

#include "BaseHasWidgets.h"
#include "HasWidgets.h"
#include "IAttributable.h"
#include "IFragment.h"
#include "ILifeCycleDecorator.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "IWidget.h"
#include "IWidgetLifeCycleListener.h"
#include "J2ObjC_source.h"
#include "LayoutTransition.h"
#include "LinearLayout.h"
#include "MeasureEvent.h"
#include "OnLayoutEvent.h"
#include "Rect.h"
#include "SnackbarContentLayout.h"
#include "SnackbarContentLayoutImpl.h"
#include "View.h"
#include "ViewGroup.h"
#include "ViewGroupImpl.h"
#include "ViewImpl.h"
#include "WidgetAttribute.h"
#include "WidgetFactory.h"
#include "java/lang/Boolean.h"
#include "java/lang/Float.h"
#include "java/lang/Integer.h"
#include "java/lang/Runnable.h"
#include "java/lang/UnsupportedOperationException.h"
#include "java/util/HashMap.h"
#include "java/util/List.h"
#include "java/util/Map.h"

#include <UIKit/UIKit.h>
#include "ASUIView.h"
#include "HasLifeCycleDecorators.h"

@protocol JavaUtilList;
@protocol JavaUtilMap;


#pragma clang diagnostic ignored "-Wprotocol"
#pragma clang diagnostic ignored "-Wincomplete-implementation"

@interface ASSnackbarContentLayoutImpl () {
 @public
  id uiView_;
  ADXSnackbarContentLayout *snackbarContentLayout_;
  ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *builder_;
  ASSnackbarContentLayoutImpl_SnackbarContentLayoutBean *bean_;
  ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *paramsBuilder_;
  ASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean *paramsBean_;
}

- (void)setWidgetOnNativeClass;

- (void)nativeRemoveViewWithASIWidget:(id<ASIWidget>)widget;

- (void)createLayoutParamsWithADView:(ADView *)view;

- (ADLinearLayout_LayoutParams *)getLayoutParamsWithADView:(ADView *)view;

@end

J2OBJC_FIELD_SETTER(ASSnackbarContentLayoutImpl, uiView_, id)
J2OBJC_FIELD_SETTER(ASSnackbarContentLayoutImpl, snackbarContentLayout_, ADXSnackbarContentLayout *)
J2OBJC_FIELD_SETTER(ASSnackbarContentLayoutImpl, builder_, ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)
J2OBJC_FIELD_SETTER(ASSnackbarContentLayoutImpl, bean_, ASSnackbarContentLayoutImpl_SnackbarContentLayoutBean *)
J2OBJC_FIELD_SETTER(ASSnackbarContentLayoutImpl, paramsBuilder_, ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *)
J2OBJC_FIELD_SETTER(ASSnackbarContentLayoutImpl, paramsBean_, ASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean *)

__attribute__((unused)) static void ASSnackbarContentLayoutImpl_setWidgetOnNativeClass(ASSnackbarContentLayoutImpl *self);

__attribute__((unused)) static void ASSnackbarContentLayoutImpl_nativeRemoveViewWithASIWidget_(ASSnackbarContentLayoutImpl *self, id<ASIWidget> widget);

__attribute__((unused)) static void ASSnackbarContentLayoutImpl_createLayoutParamsWithADView_(ASSnackbarContentLayoutImpl *self, ADView *view);

__attribute__((unused)) static ADLinearLayout_LayoutParams *ASSnackbarContentLayoutImpl_getLayoutParamsWithADView_(ASSnackbarContentLayoutImpl *self, ADView *view);

@interface ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt () {
 @public
  __unsafe_unretained ASSnackbarContentLayoutImpl *this$0_;
  ASMeasureEvent *measureFinished_;
  ASOnLayoutEvent *onLayoutEvent_;
  id<JavaUtilList> overlays_;
  jint mMaxWidth_;
  jint mMaxHeight_;
  id<JavaUtilMap> templates_;
}

@end

J2OBJC_FIELD_SETTER(ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt, measureFinished_, ASMeasureEvent *)
J2OBJC_FIELD_SETTER(ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt, onLayoutEvent_, ASOnLayoutEvent *)
J2OBJC_FIELD_SETTER(ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt, overlays_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt, templates_, id<JavaUtilMap>)

@interface ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder () {
 @public
  ASSnackbarContentLayoutImpl *this$0_;
}

@end

@interface ASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean () {
 @public
  ASSnackbarContentLayoutImpl *this$0_;
}

@end

@interface ASSnackbarContentLayoutImpl_$Lambda$1 : NSObject < JavaLangRunnable > {
 @public
  id<ASIWidget> val$widget_;
}

- (void)run;

@end

J2OBJC_EMPTY_STATIC_INIT(ASSnackbarContentLayoutImpl_$Lambda$1)

__attribute__((unused)) static void ASSnackbarContentLayoutImpl_$Lambda$1_initWithASIWidget_(ASSnackbarContentLayoutImpl_$Lambda$1 *self, id<ASIWidget> capture$0);

__attribute__((unused)) static ASSnackbarContentLayoutImpl_$Lambda$1 *new_ASSnackbarContentLayoutImpl_$Lambda$1_initWithASIWidget_(id<ASIWidget> capture$0) NS_RETURNS_RETAINED;

__attribute__((unused)) static ASSnackbarContentLayoutImpl_$Lambda$1 *create_ASSnackbarContentLayoutImpl_$Lambda$1_initWithASIWidget_(id<ASIWidget> capture$0);

NSString *ASSnackbarContentLayoutImpl_LOCAL_NAME = @"com.google.android.material.snackbar.SnackbarContentLayout";
NSString *ASSnackbarContentLayoutImpl_GROUP_NAME = @"com.google.android.material.snackbar.SnackbarContentLayout";

@implementation ASSnackbarContentLayoutImpl

@synthesize uiView = uiView_;

- (void)loadAttributesWithNSString:(NSString *)localName {
  ASViewGroupImpl_register__WithNSString_(localName);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_gravity"])) withTypeWithNSString:@"gravity"])) forChild]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_weight"])) withTypeWithNSString:@"float"])) forChild]);
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASSnackbarContentLayoutImpl_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithNSString:(NSString *)localname {
  ASSnackbarContentLayoutImpl_initWithNSString_(self, localname);
  return self;
}

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname {
  ASSnackbarContentLayoutImpl_initWithNSString_withNSString_(self, groupName, localname);
  return self;
}

- (id<ASIWidget>)newInstance {
  return new_ASSnackbarContentLayoutImpl_initWithNSString_withNSString_(groupName_, localName_);
}

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params {
  [super createWithASIFragment:fragment withJavaUtilMap:params];
  snackbarContentLayout_ = new_ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt_initWithASSnackbarContentLayoutImpl_(self);
  [self nativeCreateWithJavaUtilMap:params];
  ASViewGroupImpl_registerCommandConveterWithASIWidget_(self);
  ASSnackbarContentLayoutImpl_setWidgetOnNativeClass(self);
}

- (void)setWidgetOnNativeClass {
  ASSnackbarContentLayoutImpl_setWidgetOnNativeClass(self);
}

- (id)asWidget {
  return snackbarContentLayout_;
}

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w {
  jboolean remove = [super removeWithASIWidget:w];
  [((ADXSnackbarContentLayout *) nil_chk(snackbarContentLayout_)) removeViewWithADView:(ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class])];
  ASSnackbarContentLayoutImpl_nativeRemoveViewWithASIWidget_(self, w);
  return remove;
}

- (jboolean)removeWithInt:(jint)index {
  id<ASIWidget> widget = [((id<JavaUtilList>) nil_chk(widgets_)) getWithInt:index];
  jboolean remove = [super removeWithInt:index];
  if (index + 1 <= [((ADXSnackbarContentLayout *) nil_chk(snackbarContentLayout_)) getChildCount]) {
    [((ADXSnackbarContentLayout *) nil_chk(snackbarContentLayout_)) removeViewAtWithInt:index];
    ASSnackbarContentLayoutImpl_nativeRemoveViewWithASIWidget_(self, widget);
  }
  return remove;
}

- (void)nativeRemoveViewWithASIWidget:(id<ASIWidget>)widget {
  ASSnackbarContentLayoutImpl_nativeRemoveViewWithASIWidget_(self, widget);
}

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index {
  if (index != -2) {
    ADView *view = (ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class]);
    ASSnackbarContentLayoutImpl_createLayoutParamsWithADView_(self, view);
    if (index == -1) {
      [((ADXSnackbarContentLayout *) nil_chk(snackbarContentLayout_)) addViewWithADView:view];
    }
    else {
      [((ADXSnackbarContentLayout *) nil_chk(snackbarContentLayout_)) addViewWithADView:view withInt:index];
    }
  }
  ASViewGroupImpl_nativeAddViewWithId_withId_([self asNativeWidget], [((id<ASIWidget>) nil_chk(w)) asNativeWidget]);
  [super addWithASIWidget:w withInt:index];
}

- (void)createLayoutParamsWithADView:(ADView *)view {
  ASSnackbarContentLayoutImpl_createLayoutParamsWithADView_(self, view);
}

- (ADLinearLayout_LayoutParams *)getLayoutParamsWithADView:(ADView *)view {
  return ASSnackbarContentLayoutImpl_getLayoutParamsWithADView_(self, view);
}

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue {
  ADView *view = (ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class]);
  ADLinearLayout_LayoutParams *layoutParams = ASSnackbarContentLayoutImpl_getLayoutParamsWithADView_(self, view);
  ASViewGroupImpl_setChildAttributeWithASIWidget_withASWidgetAttribute_withId_withId_(w, key, objValue, layoutParams);
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){ @"layout_width", @"layout_height", @"layout_gravity", @"layout_weight" }, 4)) {
    case 0:
    ((ADLinearLayout_LayoutParams *) nil_chk(layoutParams))->width_ = [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue];
    break;
    case 1:
    ((ADLinearLayout_LayoutParams *) nil_chk(layoutParams))->height_ = [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue];
    break;
    case 2:
    {
      ((ADLinearLayout_LayoutParams *) nil_chk(layoutParams))->gravity_ = [((JavaLangInteger *) nil_chk(((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class])))) intValue];
    }
    break;
    case 3:
    {
      ((ADLinearLayout_LayoutParams *) nil_chk(layoutParams))->weight_ = [((JavaLangFloat *) nil_chk(((JavaLangFloat *) cast_chk(objValue, [JavaLangFloat class])))) floatValue];
    }
    break;
    default:
    break;
  }
  [((ADView *) nil_chk(view)) setLayoutParamsWithADViewGroup_LayoutParams:layoutParams];
}

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key {
  id attributeValue = ASViewGroupImpl_getChildAttributeWithASIWidget_withASWidgetAttribute_(w, key);
  if (attributeValue != nil) {
    return attributeValue;
  }
  ADView *view = (ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class]);
  ADLinearLayout_LayoutParams *layoutParams = ASSnackbarContentLayoutImpl_getLayoutParamsWithADView_(self, view);
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){ @"layout_width", @"layout_height", @"layout_gravity", @"layout_weight" }, 4)) {
    case 0:
    return JavaLangInteger_valueOfWithInt_(((ADLinearLayout_LayoutParams *) nil_chk(layoutParams))->width_);
    case 1:
    return JavaLangInteger_valueOfWithInt_(((ADLinearLayout_LayoutParams *) nil_chk(layoutParams))->height_);
    case 2:
    {
      return JavaLangInteger_valueOfWithInt_(((ADLinearLayout_LayoutParams *) nil_chk(layoutParams))->gravity_);
    }
    case 3:
    {
      return JavaLangFloat_valueOfWithFloat_(((ADLinearLayout_LayoutParams *) nil_chk(layoutParams))->weight_);
    }
  }
  return nil;
}

- (IOSClass *)getViewClass {
  return ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt_class_();
}

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator {
  ASViewGroupImpl_setAttributeWithASIWidget_withASWidgetAttribute_withNSString_withId_withASILifeCycleDecorator_(self, key, strValue, objValue, decorator);
  id nativeWidget = [self asNativeWidget];
}

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator {
  id attributeValue = ASViewGroupImpl_getAttributeWithASIWidget_withASWidgetAttribute_withASILifeCycleDecorator_(self, key, decorator);
  if (attributeValue != nil) {
    return attributeValue;
  }
  id nativeWidget = [self asNativeWidget];
  return nil;
}

- (id)asNativeWidget {
  return uiView_;
}

- (jboolean)checkIosVersionWithNSString:(NSString *)v {
  return ([[[UIDevice currentDevice] systemVersion] compare:v options:NSNumericSearch] == NSOrderedDescending);
}

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params {
  ASUIView* uiView = [ASUIView new];
  uiView.backgroundColor = [UIColor clearColor];
  uiView_ = uiView;
}

- (void)requestLayout {
  if ([self isInitialised]) {
    ASViewImpl_requestLayoutWithASIWidget_withId_(self, [self asNativeWidget]);
  }
}

- (void)invalidate {
  if ([self isInitialised]) {
    ASViewImpl_invalidateWithASIWidget_withId_(self, [self asNativeWidget]);
  }
}

- (void)setIdWithNSString:(NSString *)id_ {
  if (id_ != nil && ![id_ isEqual:@""]) {
    [super setIdWithNSString:id_];
    [((ADXSnackbarContentLayout *) nil_chk(snackbarContentLayout_)) setIdWithInt:[((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk([self quickConvertWithId:id_ withNSString:@"id"], [JavaLangInteger class]))) intValue]];
  }
}

- (void)setVisibleWithBoolean:(jboolean)b {
  [((ADView *) nil_chk(((ADView *) cast_chk([self asWidget], [ADView class])))) setVisibilityWithInt:b ? ADView_VISIBLE : ADView_GONE];
}

- (id)getPluginWithNSString:(NSString *)plugin {
  return [((id<ASIAttributable>) nil_chk(ASWidgetFactory_getAttributableWithNSString_(plugin))) newInstanceWithASIWidget:self];
}

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutBean *)getBean {
  if (bean_ == nil) {
    bean_ = new_ASSnackbarContentLayoutImpl_SnackbarContentLayoutBean_initWithASSnackbarContentLayoutImpl_(self);
  }
  return bean_;
}

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)getBuilder {
  if (builder_ == nil) {
    builder_ = new_ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder_initWithASSnackbarContentLayoutImpl_(self);
  }
  return builder_;
}

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean *)getParamsBean {
  if (paramsBean_ == nil) {
    paramsBean_ = new_ASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean_initWithASSnackbarContentLayoutImpl_(self);
  }
  return paramsBean_;
}

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *)getParamsBuilder {
  if (paramsBuilder_ == nil) {
    paramsBuilder_ = new_ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder_initWithASSnackbarContentLayoutImpl_(self);
  }
  return paramsBuilder_;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 2, -1, -1, -1, -1 },
    { NULL, "LASIWidget;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 4, -1, 5, -1, -1 },
    { NULL, "V", 0x102, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 6, 7, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 6, 8, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 9, 7, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 10, 11, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 12, 13, -1, -1, -1, -1 },
    { NULL, "LADLinearLayout_LayoutParams;", 0x2, 14, 13, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 15, 16, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 17, 18, -1, -1, -1, -1 },
    { NULL, "LIOSClass;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 19, 20, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 21, 22, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x101, 23, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x101, 24, 25, -1, 26, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 27, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 28, 29, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 30, 1, -1, -1, -1, -1 },
    { NULL, "LASSnackbarContentLayoutImpl_SnackbarContentLayoutBean;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(loadAttributesWithNSString:);
  methods[1].selector = @selector(init);
  methods[2].selector = @selector(initWithNSString:);
  methods[3].selector = @selector(initWithNSString:withNSString:);
  methods[4].selector = @selector(newInstance);
  methods[5].selector = @selector(createWithASIFragment:withJavaUtilMap:);
  methods[6].selector = @selector(setWidgetOnNativeClass);
  methods[7].selector = @selector(asWidget);
  methods[8].selector = @selector(removeWithASIWidget:);
  methods[9].selector = @selector(removeWithInt:);
  methods[10].selector = @selector(nativeRemoveViewWithASIWidget:);
  methods[11].selector = @selector(addWithASIWidget:withInt:);
  methods[12].selector = @selector(createLayoutParamsWithADView:);
  methods[13].selector = @selector(getLayoutParamsWithADView:);
  methods[14].selector = @selector(setChildAttributeWithASIWidget:withASWidgetAttribute:withNSString:withId:);
  methods[15].selector = @selector(getChildAttributeWithASIWidget:withASWidgetAttribute:);
  methods[16].selector = @selector(getViewClass);
  methods[17].selector = @selector(setAttributeWithASWidgetAttribute:withNSString:withId:withASILifeCycleDecorator:);
  methods[18].selector = @selector(getAttributeWithASWidgetAttribute:withASILifeCycleDecorator:);
  methods[19].selector = @selector(asNativeWidget);
  methods[20].selector = @selector(checkIosVersionWithNSString:);
  methods[21].selector = @selector(nativeCreateWithJavaUtilMap:);
  methods[22].selector = @selector(requestLayout);
  methods[23].selector = @selector(invalidate);
  methods[24].selector = @selector(setIdWithNSString:);
  methods[25].selector = @selector(setVisibleWithBoolean:);
  methods[26].selector = @selector(getPluginWithNSString:);
  methods[27].selector = @selector(getBean);
  methods[28].selector = @selector(getBuilder);
  methods[29].selector = @selector(getParamsBean);
  methods[30].selector = @selector(getParamsBuilder);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "uiView_", "LNSObject;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "LOCAL_NAME", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 31, -1, -1 },
    { "GROUP_NAME", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 32, -1, -1 },
    { "snackbarContentLayout_", "LADXSnackbarContentLayout;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "builder_", "LASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "bean_", "LASSnackbarContentLayoutImpl_SnackbarContentLayoutBean;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "paramsBuilder_", "LASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "paramsBean_", "LASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "loadAttributes", "LNSString;", "LNSString;LNSString;", "create", "LASIFragment;LJavaUtilMap;", "(Lcom/ashera/core/IFragment;Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;)V", "remove", "LASIWidget;", "I", "nativeRemoveView", "add", "LASIWidget;I", "createLayoutParams", "LADView;", "getLayoutParams", "setChildAttribute", "LASIWidget;LASWidgetAttribute;LNSString;LNSObject;", "getChildAttribute", "LASIWidget;LASWidgetAttribute;", "setAttribute", "LASWidgetAttribute;LNSString;LNSObject;LASILifeCycleDecorator;", "getAttribute", "LASWidgetAttribute;LASILifeCycleDecorator;", "checkIosVersion", "nativeCreate", "LJavaUtilMap;", "(Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;)V", "setId", "setVisible", "Z", "getPlugin", &ASSnackbarContentLayoutImpl_LOCAL_NAME, &ASSnackbarContentLayoutImpl_GROUP_NAME, "LASSnackbarContentLayoutImpl_SnackbarContentLayoutExt;LASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder;LASSnackbarContentLayoutImpl_SnackbarContentLayoutBean;LASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean;LASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder;" };
  static const J2ObjcClassInfo _ASSnackbarContentLayoutImpl = { "SnackbarContentLayoutImpl", "com.ashera.snackbar", ptrTable, methods, fields, 7, 0x1, 31, 8, -1, 33, -1, -1, -1 };
  return &_ASSnackbarContentLayoutImpl;
}

@end

void ASSnackbarContentLayoutImpl_init(ASSnackbarContentLayoutImpl *self) {
  ASBaseHasWidgets_initWithNSString_withNSString_(self, ASSnackbarContentLayoutImpl_GROUP_NAME, ASSnackbarContentLayoutImpl_LOCAL_NAME);
}

ASSnackbarContentLayoutImpl *new_ASSnackbarContentLayoutImpl_init() {
  J2OBJC_NEW_IMPL(ASSnackbarContentLayoutImpl, init)
}

ASSnackbarContentLayoutImpl *create_ASSnackbarContentLayoutImpl_init() {
  J2OBJC_CREATE_IMPL(ASSnackbarContentLayoutImpl, init)
}

void ASSnackbarContentLayoutImpl_initWithNSString_(ASSnackbarContentLayoutImpl *self, NSString *localname) {
  ASBaseHasWidgets_initWithNSString_withNSString_(self, ASSnackbarContentLayoutImpl_GROUP_NAME, localname);
}

ASSnackbarContentLayoutImpl *new_ASSnackbarContentLayoutImpl_initWithNSString_(NSString *localname) {
  J2OBJC_NEW_IMPL(ASSnackbarContentLayoutImpl, initWithNSString_, localname)
}

ASSnackbarContentLayoutImpl *create_ASSnackbarContentLayoutImpl_initWithNSString_(NSString *localname) {
  J2OBJC_CREATE_IMPL(ASSnackbarContentLayoutImpl, initWithNSString_, localname)
}

void ASSnackbarContentLayoutImpl_initWithNSString_withNSString_(ASSnackbarContentLayoutImpl *self, NSString *groupName, NSString *localname) {
  ASBaseHasWidgets_initWithNSString_withNSString_(self, groupName, localname);
}

ASSnackbarContentLayoutImpl *new_ASSnackbarContentLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) {
  J2OBJC_NEW_IMPL(ASSnackbarContentLayoutImpl, initWithNSString_withNSString_, groupName, localname)
}

ASSnackbarContentLayoutImpl *create_ASSnackbarContentLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) {
  J2OBJC_CREATE_IMPL(ASSnackbarContentLayoutImpl, initWithNSString_withNSString_, groupName, localname)
}

void ASSnackbarContentLayoutImpl_setWidgetOnNativeClass(ASSnackbarContentLayoutImpl *self) {
  ((ASUIView*) [self asNativeWidget]).widget = self;
}

void ASSnackbarContentLayoutImpl_nativeRemoveViewWithASIWidget_(ASSnackbarContentLayoutImpl *self, id<ASIWidget> widget) {
  ADLayoutTransition *layoutTransition = [((ADXSnackbarContentLayout *) nil_chk(self->snackbarContentLayout_)) getLayoutTransition];
  if (layoutTransition != nil && ([layoutTransition isTransitionTypeEnabledWithInt:ADLayoutTransition_CHANGE_DISAPPEARING] || [layoutTransition isTransitionTypeEnabledWithInt:ADLayoutTransition_DISAPPEARING])) {
    [self addToBufferedRunnablesWithJavaLangRunnable:new_ASSnackbarContentLayoutImpl_$Lambda$1_initWithASIWidget_(widget)];
  }
  else {
    ASViewGroupImpl_nativeRemoveViewWithASIWidget_(widget);
  }
}

void ASSnackbarContentLayoutImpl_createLayoutParamsWithADView_(ASSnackbarContentLayoutImpl *self, ADView *view) {
  ADLinearLayout_LayoutParams *layoutParams = (ADLinearLayout_LayoutParams *) cast_chk([((ADView *) nil_chk(view)) getLayoutParams], [ADLinearLayout_LayoutParams class]);
  layoutParams = (ADLinearLayout_LayoutParams *) cast_chk([view getLayoutParams], [ADLinearLayout_LayoutParams class]);
  if (layoutParams == nil) {
    layoutParams = new_ADLinearLayout_LayoutParams_initWithInt_withInt_(-2, -2);
    [view setLayoutParamsWithADViewGroup_LayoutParams:layoutParams];
  }
  else {
    layoutParams->height_ = -2;
    layoutParams->width_ = -2;
  }
}

ADLinearLayout_LayoutParams *ASSnackbarContentLayoutImpl_getLayoutParamsWithADView_(ASSnackbarContentLayoutImpl *self, ADView *view) {
  return (ADLinearLayout_LayoutParams *) cast_chk([((ADView *) nil_chk(view)) getLayoutParams], [ADLinearLayout_LayoutParams class]);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASSnackbarContentLayoutImpl)

@implementation ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt

- (id<ASIWidget>)getWidget {
  return this$0_;
}

- (void)setMaxWidthWithInt:(jint)width {
  mMaxWidth_ = width;
}

- (void)setMaxHeightWithInt:(jint)height {
  mMaxHeight_ = height;
}

- (jint)getMaxWidth {
  return mMaxWidth_;
}

- (jint)getMaxHeight {
  return mMaxHeight_;
}

- (instancetype)initWithASSnackbarContentLayoutImpl:(ASSnackbarContentLayoutImpl *)outer$ {
  ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt_initWithASSnackbarContentLayoutImpl_(self, outer$);
  return self;
}

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec {
  if (mMaxWidth_ > 0) {
    widthMeasureSpec = ADView_MeasureSpec_makeMeasureSpecWithInt_withInt_(mMaxWidth_, ADView_MeasureSpec_AT_MOST);
  }
  if (mMaxHeight_ > 0) {
    heightMeasureSpec = ADView_MeasureSpec_makeMeasureSpecWithInt_withInt_(mMaxHeight_, ADView_MeasureSpec_AT_MOST);
  }
  [super onMeasureWithInt:widthMeasureSpec withInt:heightMeasureSpec];
  id<ASIWidgetLifeCycleListener> listener = [this$0_ getListener];
  if (listener != nil) {
    [((ASMeasureEvent *) nil_chk(measureFinished_)) setWidthWithInt:[self getMeasuredWidth]];
    [((ASMeasureEvent *) nil_chk(measureFinished_)) setHeightWithInt:[self getMeasuredHeight]];
    [listener eventOccurredWithASIWidgetLifeCycleListener_EventId:JreLoadEnum(ASIWidgetLifeCycleListener_EventId, measureFinished) withASWidgetEvent:measureFinished_];
  }
}

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b {
  [super onLayoutWithBoolean:changed withInt:l withInt:t withInt:r withInt:b];
  ASViewImpl_setDrawableBoundsWithASIWidget_withInt_withInt_withInt_withInt_(this$0_, l, t, r, b);
  if (![self isOverlay]) {
    ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$0_ asNativeWidget], l, t, r, b);
  }
  [this$0_ replayBufferedEvents];
  ASViewImpl_redrawDrawablesWithASIWidget_(this$0_);
  overlays_ = ASViewImpl_drawOverlayWithASIWidget_withJavaUtilList_(this$0_, overlays_);
  id<ASIWidgetLifeCycleListener> listener = [this$0_ getListener];
  if (listener != nil) {
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setBWithInt:b];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setLWithInt:l];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setRWithInt:r];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setTWithInt:t];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setChangedWithBoolean:changed];
    [listener eventOccurredWithASIWidgetLifeCycleListener_EventId:JreLoadEnum(ASIWidgetLifeCycleListener_EventId, onLayout) withASWidgetEvent:onLayoutEvent_];
  }
  if ([this$0_ isInvalidateOnFrameChange] && [this$0_ isInitialised]) {
    [this$0_ invalidate];
  }
}

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas {
}

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height {
  [self setMeasuredDimensionWithInt:width withInt:height];
}

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (id<JavaUtilList>)getMethods {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)initialized {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)drawableStateChanged {
  [super drawableStateChanged];
  if (![this$0_ isWidgetDisposed]) {
    ASViewImpl_drawableStateChangedWithASIWidget_(this$0_);
  }
}

- (ADView *)inflateViewWithNSString:(NSString *)layout {
  if (templates_ == nil) {
    templates_ = new_JavaUtilHashMap_init();
  }
  id<ASIWidget> template_ = [templates_ getWithId:layout];
  if (template_ == nil) {
    template_ = (id<ASIWidget>) cast_check([this$0_ quickConvertWithId:layout withNSString:@"template"], ASIWidget_class_());
    (void) [((id<JavaUtilMap>) nil_chk(templates_)) putWithId:layout withId:template_];
  }
  id<ASIWidget> widget = [((id<ASIWidget>) nil_chk(template_)) loadLazyWidgetsWithASHasWidgets:this$0_];
  return (ADView *) cast_chk([((id<ASIWidget>) nil_chk(widget)) asWidget], [ADView class]);
}

- (void)remeasure {
  if ([this$0_ getFragment] != nil) {
    [((id<ASIFragment>) nil_chk([this$0_ getFragment])) remeasure];
  }
}

- (void)removeFromParent {
  [((id<ASHasWidgets>) nil_chk([this$0_ getParent])) removeWithASIWidget:this$0_];
}

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation {
  *IOSIntArray_GetRef(nil_chk(appScreenLocation), 0) = ASViewImpl_getLocationXOnScreenWithId_([this$0_ asNativeWidget]);
  *IOSIntArray_GetRef(appScreenLocation, 1) = ASViewImpl_getLocationYOnScreenWithId_([this$0_ asNativeWidget]);
}

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame {
  ((ADRect *) nil_chk(displayFrame))->left_ = ASViewImpl_getLocationXOnScreenWithId_([this$0_ asNativeWidget]);
  displayFrame->top_ = ASViewImpl_getLocationYOnScreenWithId_([this$0_ asNativeWidget]);
  displayFrame->right_ = displayFrame->left_ + [self getWidth];
  displayFrame->bottom_ = displayFrame->top_ + [self getHeight];
}

- (void)offsetTopAndBottomWithInt:(jint)offset {
  [super offsetTopAndBottomWithInt:offset];
  ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$0_ asNativeWidget], [self getLeft], [self getTop], [self getRight], [self getBottom]);
}

- (void)offsetLeftAndRightWithInt:(jint)offset {
  [super offsetLeftAndRightWithInt:offset];
  ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$0_ asNativeWidget], [self getLeft], [self getTop], [self getRight], [self getBottom]);
}

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value {
  if ([((NSString *) nil_chk(name)) isEqual:@"state0"]) {
    [self setState0WithId:value];
    return;
  }
  if ([name isEqual:@"state1"]) {
    [self setState1WithId:value];
    return;
  }
  if ([name isEqual:@"state2"]) {
    [self setState2WithId:value];
    return;
  }
  if ([name isEqual:@"state3"]) {
    [self setState3WithId:value];
    return;
  }
  if ([name isEqual:@"state4"]) {
    [self setState4WithId:value];
    return;
  }
  [this$0_ setAttributeWithNSString:name withId:value withBoolean:!([value isKindOfClass:[NSString class]])];
}

- (void)setVisibilityWithInt:(jint)visibility {
  [super setVisibilityWithInt:visibility];
  ASViewImpl_nativeSetVisibilityWithId_withBoolean_([this$0_ asNativeWidget], visibility != ADView_VISIBLE);
}

- (void)setState0WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 0, value);
}

- (void)setState1WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 1, value);
}

- (void)setState2WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 2, value);
}

- (void)setState3WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 3, value);
}

- (void)setState4WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 4, value);
}

- (void)state0 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 0);
}

- (void)state1 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 1);
}

- (void)state2 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 2);
}

- (void)state3 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 3);
}

- (void)state4 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 4);
}

- (void)stateYes {
  ASViewImpl_stateYesWithASIWidget_(this$0_);
}

- (void)stateNo {
  ASViewImpl_stateNoWithASIWidget_(this$0_);
}

- (void)endViewTransitionWithADView:(ADView *)view {
  [super endViewTransitionWithADView:view];
  [this$0_ runBufferedRunnables];
}

- (void)__javaClone:(ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt *)original {
  [super __javaClone:original];
  JreRelease(this$0_);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LASIWidget;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 2, 1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 4, 5, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 6, 7, -1, -1, -1, -1 },
    { NULL, "V", 0x81, 8, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 10, 5, -1, -1, -1, -1 },
    { NULL, "LASILifeCycleDecorator;", 0x1, 11, 12, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 13, 14, -1, -1, -1, -1 },
    { NULL, "LJavaUtilList;", 0x1, -1, -1, -1, 15, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 16, 17, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LADView;", 0x1, 18, 19, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 20, 21, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 22, 23, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 24, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 25, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 26, 27, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 28, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 29, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 31, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 32, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 33, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 34, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 35, 36, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(getWidget);
  methods[1].selector = @selector(setMaxWidthWithInt:);
  methods[2].selector = @selector(setMaxHeightWithInt:);
  methods[3].selector = @selector(getMaxWidth);
  methods[4].selector = @selector(getMaxHeight);
  methods[5].selector = @selector(initWithASSnackbarContentLayoutImpl:);
  methods[6].selector = @selector(onMeasureWithInt:withInt:);
  methods[7].selector = @selector(onLayoutWithBoolean:withInt:withInt:withInt:withInt:);
  methods[8].selector = @selector(executeWithNSString:withNSObjectArray:);
  methods[9].selector = @selector(updateMeasuredDimensionWithInt:withInt:);
  methods[10].selector = @selector(newInstanceWithASIWidget:);
  methods[11].selector = @selector(setAttributeWithASWidgetAttribute:withNSString:withId:);
  methods[12].selector = @selector(getMethods);
  methods[13].selector = @selector(initialized);
  methods[14].selector = @selector(getAttributeWithASWidgetAttribute:);
  methods[15].selector = @selector(drawableStateChanged);
  methods[16].selector = @selector(inflateViewWithNSString:);
  methods[17].selector = @selector(remeasure);
  methods[18].selector = @selector(removeFromParent);
  methods[19].selector = @selector(getLocationOnScreenWithIntArray:);
  methods[20].selector = @selector(getWindowVisibleDisplayFrameWithADRect:);
  methods[21].selector = @selector(offsetTopAndBottomWithInt:);
  methods[22].selector = @selector(offsetLeftAndRightWithInt:);
  methods[23].selector = @selector(setMyAttributeWithNSString:withId:);
  methods[24].selector = @selector(setVisibilityWithInt:);
  methods[25].selector = @selector(setState0WithId:);
  methods[26].selector = @selector(setState1WithId:);
  methods[27].selector = @selector(setState2WithId:);
  methods[28].selector = @selector(setState3WithId:);
  methods[29].selector = @selector(setState4WithId:);
  methods[30].selector = @selector(state0);
  methods[31].selector = @selector(state1);
  methods[32].selector = @selector(state2);
  methods[33].selector = @selector(state3);
  methods[34].selector = @selector(state4);
  methods[35].selector = @selector(stateYes);
  methods[36].selector = @selector(stateNo);
  methods[37].selector = @selector(endViewTransitionWithADView:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LASSnackbarContentLayoutImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "measureFinished_", "LASMeasureEvent;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "onLayoutEvent_", "LASOnLayoutEvent;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "overlays_", "LJavaUtilList;", .constantValue.asLong = 0, 0x2, -1, -1, 37, -1 },
    { "mMaxWidth_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "mMaxHeight_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "templates_", "LJavaUtilMap;", .constantValue.asLong = 0, 0x2, -1, -1, 38, -1 },
  };
  static const void *ptrTable[] = { "setMaxWidth", "I", "setMaxHeight", "LASSnackbarContentLayoutImpl;", "onMeasure", "II", "onLayout", "ZIIII", "execute", "LNSString;[LNSObject;", "updateMeasuredDimension", "newInstance", "LASIWidget;", "setAttribute", "LASWidgetAttribute;LNSString;LNSObject;", "()Ljava/util/List<Ljava/lang/String;>;", "getAttribute", "LASWidgetAttribute;", "inflateView", "LNSString;", "getLocationOnScreen", "[I", "getWindowVisibleDisplayFrame", "LADRect;", "offsetTopAndBottom", "offsetLeftAndRight", "setMyAttribute", "LNSString;LNSObject;", "setVisibility", "setState0", "LNSObject;", "setState1", "setState2", "setState3", "setState4", "endViewTransition", "LADView;", "Ljava/util/List<Lcom/ashera/widget/IWidget;>;", "Ljava/util/Map<Ljava/lang/String;Lcom/ashera/widget/IWidget;>;" };
  static const J2ObjcClassInfo _ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt = { "SnackbarContentLayoutExt", "com.ashera.snackbar", ptrTable, methods, fields, 7, 0x1, 38, 7, 3, -1, -1, -1, -1 };
  return &_ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt;
}

@end

void ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt_initWithASSnackbarContentLayoutImpl_(ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt *self, ASSnackbarContentLayoutImpl *outer$) {
  self->this$0_ = outer$;
  ADXSnackbarContentLayout_init(self);
  self->measureFinished_ = new_ASMeasureEvent_init();
  self->onLayoutEvent_ = new_ASOnLayoutEvent_init();
  self->mMaxWidth_ = -1;
  self->mMaxHeight_ = -1;
}

ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt *new_ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt_initWithASSnackbarContentLayoutImpl_(ASSnackbarContentLayoutImpl *outer$) {
  J2OBJC_NEW_IMPL(ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt, initWithASSnackbarContentLayoutImpl_, outer$)
}

ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt *create_ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt_initWithASSnackbarContentLayoutImpl_(ASSnackbarContentLayoutImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt, initWithASSnackbarContentLayoutImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt)

@implementation ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder

- (instancetype)initWithASSnackbarContentLayoutImpl:(ASSnackbarContentLayoutImpl *)outer$ {
  ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder_initWithASSnackbarContentLayoutImpl_(self, outer$);
  return self;
}

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)executeWithBoolean:(jboolean)setter {
  if (setter) {
    [this$0_ executeCommandWithJavaUtilMap:command_ withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_SETTER_METHOD];
    [((id<ASIFragment>) nil_chk([this$0_ getFragment])) remeasure];
  }
  [this$0_ executeCommandWithJavaUtilMap:command_ withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_GETTER_METHOD];
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder;", 0x1, 1, 2, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASSnackbarContentLayoutImpl:);
  methods[1].selector = @selector(executeWithBoolean:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LASSnackbarContentLayoutImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LASSnackbarContentLayoutImpl;", "execute", "Z", "Lcom/ashera/layout/ViewGroupImpl$ViewGroupCommandBuilder<Lcom/ashera/snackbar/SnackbarContentLayoutImpl$SnackbarContentLayoutCommandBuilder;>;" };
  static const J2ObjcClassInfo _ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder = { "SnackbarContentLayoutCommandBuilder", "com.ashera.snackbar", ptrTable, methods, fields, 7, 0x1, 2, 1, 0, -1, -1, 3, -1 };
  return &_ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder;
}

@end

void ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder_initWithASSnackbarContentLayoutImpl_(ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *self, ASSnackbarContentLayoutImpl *outer$) {
  self->this$0_ = outer$;
  ASViewGroupImpl_ViewGroupCommandBuilder_init(self);
}

ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *new_ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder_initWithASSnackbarContentLayoutImpl_(ASSnackbarContentLayoutImpl *outer$) {
  J2OBJC_NEW_IMPL(ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder, initWithASSnackbarContentLayoutImpl_, outer$)
}

ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *create_ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder_initWithASSnackbarContentLayoutImpl_(ASSnackbarContentLayoutImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder, initWithASSnackbarContentLayoutImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder)

@implementation ASSnackbarContentLayoutImpl_SnackbarContentLayoutBean

- (instancetype)initWithASSnackbarContentLayoutImpl:(ASSnackbarContentLayoutImpl *)outer$ {
  ASSnackbarContentLayoutImpl_SnackbarContentLayoutBean_initWithASSnackbarContentLayoutImpl_(self, outer$);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASSnackbarContentLayoutImpl:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LASSnackbarContentLayoutImpl;" };
  static const J2ObjcClassInfo _ASSnackbarContentLayoutImpl_SnackbarContentLayoutBean = { "SnackbarContentLayoutBean", "com.ashera.snackbar", ptrTable, methods, NULL, 7, 0x1, 1, 0, 0, -1, -1, -1, -1 };
  return &_ASSnackbarContentLayoutImpl_SnackbarContentLayoutBean;
}

@end

void ASSnackbarContentLayoutImpl_SnackbarContentLayoutBean_initWithASSnackbarContentLayoutImpl_(ASSnackbarContentLayoutImpl_SnackbarContentLayoutBean *self, ASSnackbarContentLayoutImpl *outer$) {
  ASViewGroupImpl_ViewGroupBean_initWithASIWidget_(self, outer$);
}

ASSnackbarContentLayoutImpl_SnackbarContentLayoutBean *new_ASSnackbarContentLayoutImpl_SnackbarContentLayoutBean_initWithASSnackbarContentLayoutImpl_(ASSnackbarContentLayoutImpl *outer$) {
  J2OBJC_NEW_IMPL(ASSnackbarContentLayoutImpl_SnackbarContentLayoutBean, initWithASSnackbarContentLayoutImpl_, outer$)
}

ASSnackbarContentLayoutImpl_SnackbarContentLayoutBean *create_ASSnackbarContentLayoutImpl_SnackbarContentLayoutBean_initWithASSnackbarContentLayoutImpl_(ASSnackbarContentLayoutImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASSnackbarContentLayoutImpl_SnackbarContentLayoutBean, initWithASSnackbarContentLayoutImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASSnackbarContentLayoutImpl_SnackbarContentLayoutBean)

@implementation ASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean

- (instancetype)initWithASSnackbarContentLayoutImpl:(ASSnackbarContentLayoutImpl *)outer$ {
  ASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean_initWithASSnackbarContentLayoutImpl_(self, outer$);
  return self;
}

- (id)getLayoutGravityWithASIWidget:(id<ASIWidget>)w {
  id<JavaUtilMap> layoutParams = new_JavaUtilHashMap_init();
  id<JavaUtilMap> command = [((ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *) nil_chk([((ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *) nil_chk([((ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) reset])) tryGetLayoutGravity])) getCommand];
  (void) [layoutParams putWithId:@"layoutParams" withId:command];
  [((id<ASIWidget>) nil_chk(w)) executeCommandWithJavaUtilMap:layoutParams withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_GETTER_METHOD];
  return [((ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) getLayoutGravity];
}

- (void)setLayoutGravityWithASIWidget:(id<ASIWidget>)w
                         withNSString:(NSString *)value {
  id<JavaUtilMap> layoutParams = new_JavaUtilHashMap_init();
  (void) [layoutParams putWithId:@"layoutParams" withId:[((ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *) nil_chk([((ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *) nil_chk([((ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) reset])) setLayoutGravityWithNSString:value])) getCommand]];
  [((id<ASIWidget>) nil_chk(w)) executeCommandWithJavaUtilMap:layoutParams withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_SETTER_METHOD];
  [((id<ASIFragment>) nil_chk([w getFragment])) remeasure];
}

- (id)getLayoutWeightWithASIWidget:(id<ASIWidget>)w {
  id<JavaUtilMap> layoutParams = new_JavaUtilHashMap_init();
  id<JavaUtilMap> command = [((ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *) nil_chk([((ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *) nil_chk([((ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) reset])) tryGetLayoutWeight])) getCommand];
  (void) [layoutParams putWithId:@"layoutParams" withId:command];
  [((id<ASIWidget>) nil_chk(w)) executeCommandWithJavaUtilMap:layoutParams withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_GETTER_METHOD];
  return [((ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) getLayoutWeight];
}

- (void)setLayoutWeightWithASIWidget:(id<ASIWidget>)w
                           withFloat:(jfloat)value {
  id<JavaUtilMap> layoutParams = new_JavaUtilHashMap_init();
  (void) [layoutParams putWithId:@"layoutParams" withId:[((ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *) nil_chk([((ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *) nil_chk([((ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) reset])) setLayoutWeightWithFloat:value])) getCommand]];
  [((id<ASIWidget>) nil_chk(w)) executeCommandWithJavaUtilMap:layoutParams withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_SETTER_METHOD];
  [((id<ASIFragment>) nil_chk([w getFragment])) remeasure];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 4, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 5, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 6, 7, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASSnackbarContentLayoutImpl:);
  methods[1].selector = @selector(getLayoutGravityWithASIWidget:);
  methods[2].selector = @selector(setLayoutGravityWithASIWidget:withNSString:);
  methods[3].selector = @selector(getLayoutWeightWithASIWidget:);
  methods[4].selector = @selector(setLayoutWeightWithASIWidget:withFloat:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LASSnackbarContentLayoutImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LASSnackbarContentLayoutImpl;", "getLayoutGravity", "LASIWidget;", "setLayoutGravity", "LASIWidget;LNSString;", "getLayoutWeight", "setLayoutWeight", "LASIWidget;F" };
  static const J2ObjcClassInfo _ASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean = { "SnackbarContentLayoutParamsBean", "com.ashera.snackbar", ptrTable, methods, fields, 7, 0x1, 5, 1, 0, -1, -1, -1, -1 };
  return &_ASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean;
}

@end

void ASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean_initWithASSnackbarContentLayoutImpl_(ASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean *self, ASSnackbarContentLayoutImpl *outer$) {
  self->this$0_ = outer$;
  ASViewGroupImpl_ViewGroupParamsBean_init(self);
}

ASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean *new_ASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean_initWithASSnackbarContentLayoutImpl_(ASSnackbarContentLayoutImpl *outer$) {
  J2OBJC_NEW_IMPL(ASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean, initWithASSnackbarContentLayoutImpl_, outer$)
}

ASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean *create_ASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean_initWithASSnackbarContentLayoutImpl_(ASSnackbarContentLayoutImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean, initWithASSnackbarContentLayoutImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean)

@implementation ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder

- (instancetype)initWithASSnackbarContentLayoutImpl:(ASSnackbarContentLayoutImpl *)outer$ {
  ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder_initWithASSnackbarContentLayoutImpl_(self, outer$);
  return self;
}

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *)tryGetLayoutGravity {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_gravity"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"getter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderGet" withId:JavaLangInteger_valueOfWithInt_(++orderGet_)];
  return self;
}

- (id)getLayoutGravity {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_gravity"];
  return [((id<JavaUtilMap>) nil_chk(attrs)) getWithId:@"commandReturnValue"];
}

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *)setLayoutGravityWithNSString:(NSString *)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_gravity"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:value];
  return self;
}

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *)tryGetLayoutWeight {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_weight"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"getter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderGet" withId:JavaLangInteger_valueOfWithInt_(++orderGet_)];
  return self;
}

- (id)getLayoutWeight {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_weight"];
  return [((id<JavaUtilMap>) nil_chk(attrs)) getWithId:@"commandReturnValue"];
}

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *)setLayoutWeightWithFloat:(jfloat)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_weight"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:JavaLangFloat_valueOfWithFloat_(value)];
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder;", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "LASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder;", 0x1, 3, 4, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASSnackbarContentLayoutImpl:);
  methods[1].selector = @selector(tryGetLayoutGravity);
  methods[2].selector = @selector(getLayoutGravity);
  methods[3].selector = @selector(setLayoutGravityWithNSString:);
  methods[4].selector = @selector(tryGetLayoutWeight);
  methods[5].selector = @selector(getLayoutWeight);
  methods[6].selector = @selector(setLayoutWeightWithFloat:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LASSnackbarContentLayoutImpl;", "setLayoutGravity", "LNSString;", "setLayoutWeight", "F", "Lcom/ashera/layout/ViewGroupImpl$ViewGroupCommandParamsBuilder<Lcom/ashera/snackbar/SnackbarContentLayoutImpl$SnackbarContentLayoutCommandParamsBuilder;>;" };
  static const J2ObjcClassInfo _ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder = { "SnackbarContentLayoutCommandParamsBuilder", "com.ashera.snackbar", ptrTable, methods, NULL, 7, 0x1, 7, 0, 0, -1, -1, 5, -1 };
  return &_ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder;
}

@end

void ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder_initWithASSnackbarContentLayoutImpl_(ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *self, ASSnackbarContentLayoutImpl *outer$) {
  ASViewGroupImpl_ViewGroupCommandParamsBuilder_init(self);
}

ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *new_ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder_initWithASSnackbarContentLayoutImpl_(ASSnackbarContentLayoutImpl *outer$) {
  J2OBJC_NEW_IMPL(ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder, initWithASSnackbarContentLayoutImpl_, outer$)
}

ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *create_ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder_initWithASSnackbarContentLayoutImpl_(ASSnackbarContentLayoutImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder, initWithASSnackbarContentLayoutImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder)

@implementation ASSnackbarContentLayoutImpl_$Lambda$1

- (void)run {
  ASViewGroupImpl_nativeRemoveViewWithASIWidget_(val$widget_);
}

@end

void ASSnackbarContentLayoutImpl_$Lambda$1_initWithASIWidget_(ASSnackbarContentLayoutImpl_$Lambda$1 *self, id<ASIWidget> capture$0) {
  self->val$widget_ = capture$0;
  NSObject_init(self);
}

ASSnackbarContentLayoutImpl_$Lambda$1 *new_ASSnackbarContentLayoutImpl_$Lambda$1_initWithASIWidget_(id<ASIWidget> capture$0) {
  J2OBJC_NEW_IMPL(ASSnackbarContentLayoutImpl_$Lambda$1, initWithASIWidget_, capture$0)
}

ASSnackbarContentLayoutImpl_$Lambda$1 *create_ASSnackbarContentLayoutImpl_$Lambda$1_initWithASIWidget_(id<ASIWidget> capture$0) {
  J2OBJC_CREATE_IMPL(ASSnackbarContentLayoutImpl_$Lambda$1, initWithASIWidget_, capture$0)
}
