//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSSnackbarPlugin\src\main\java\com\ashera\snackbar\SnackbarContentLayoutImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_SnackbarContentLayoutImpl")
#ifdef RESTRICT_SnackbarContentLayoutImpl
#define INCLUDE_ALL_SnackbarContentLayoutImpl 0
#else
#define INCLUDE_ALL_SnackbarContentLayoutImpl 1
#endif
#undef RESTRICT_SnackbarContentLayoutImpl

#if !defined (ASSnackbarContentLayoutImpl_) && (INCLUDE_ALL_SnackbarContentLayoutImpl || defined(INCLUDE_ASSnackbarContentLayoutImpl))
#define ASSnackbarContentLayoutImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASSnackbarContentLayoutImpl_SnackbarContentLayoutBean;
@class ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder;
@class ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder;
@class ASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean;
@class ASWidgetAttribute;
@class IOSClass;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASSnackbarContentLayoutImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutBean *)getBean;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)getBuilder;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean *)getParamsBean;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *)getParamsBuilder;

- (id)getPluginWithNSString:(NSString *)plugin;

- (IOSClass *)getViewClass;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (jboolean)removeWithInt:(jint)index;

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASSnackbarContentLayoutImpl)

inline NSString *ASSnackbarContentLayoutImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASSnackbarContentLayoutImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASSnackbarContentLayoutImpl, LOCAL_NAME, NSString *)

inline NSString *ASSnackbarContentLayoutImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASSnackbarContentLayoutImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASSnackbarContentLayoutImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASSnackbarContentLayoutImpl_init(ASSnackbarContentLayoutImpl *self);

FOUNDATION_EXPORT ASSnackbarContentLayoutImpl *new_ASSnackbarContentLayoutImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSnackbarContentLayoutImpl *create_ASSnackbarContentLayoutImpl_init(void);

FOUNDATION_EXPORT void ASSnackbarContentLayoutImpl_initWithNSString_(ASSnackbarContentLayoutImpl *self, NSString *localname);

FOUNDATION_EXPORT ASSnackbarContentLayoutImpl *new_ASSnackbarContentLayoutImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSnackbarContentLayoutImpl *create_ASSnackbarContentLayoutImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASSnackbarContentLayoutImpl_initWithNSString_withNSString_(ASSnackbarContentLayoutImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASSnackbarContentLayoutImpl *new_ASSnackbarContentLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSnackbarContentLayoutImpl *create_ASSnackbarContentLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASSnackbarContentLayoutImpl)

@compatibility_alias ComAsheraSnackbarSnackbarContentLayoutImpl ASSnackbarContentLayoutImpl;

#endif

#if !defined (ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt_) && (INCLUDE_ALL_SnackbarContentLayoutImpl || defined(INCLUDE_ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt))
#define ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt_

#define RESTRICT_SnackbarContentLayout 1
#define INCLUDE_ADXSnackbarContentLayout 1
#include "SnackbarContentLayout.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASSnackbarContentLayoutImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt : ADXSnackbarContentLayout < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASSnackbarContentLayoutImpl:(ASSnackbarContentLayoutImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (jint)getMaxHeight;

- (jint)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(jint)height;

- (void)setMaxWidthWithInt:(jint)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt)

FOUNDATION_EXPORT void ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt_initWithASSnackbarContentLayoutImpl_(ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt *self, ASSnackbarContentLayoutImpl *outer$);

FOUNDATION_EXPORT ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt *new_ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt_initWithASSnackbarContentLayoutImpl_(ASSnackbarContentLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt *create_ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt_initWithASSnackbarContentLayoutImpl_(ASSnackbarContentLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASSnackbarContentLayoutImpl_SnackbarContentLayoutExt)

#endif

#if !defined (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder_) && (INCLUDE_ALL_SnackbarContentLayoutImpl || defined(INCLUDE_ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder))
#define ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupCommandBuilder 1
#include "ViewGroupImpl.h"

@class ASSnackbarContentLayoutImpl;

@interface ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder : ASViewGroupImpl_ViewGroupCommandBuilder

#pragma mark Public

- (instancetype)initWithASSnackbarContentLayoutImpl:(ASSnackbarContentLayoutImpl *)outer$;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)addAllModelWithId:(id)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)addModelByIndexWithId:(id)arg0
                                                                                    withId:(id)arg1;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)addModelWithId:(id)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)animatorXmlWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)endAnimator;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)executeWithBoolean:(jboolean)setter;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)invalidate;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)notifyDataSetChangedWithBoolean:(jboolean)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)refreshUiFromModelWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)removeModelAtIndexWithInt:(jint)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)removeModelByIdWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)requestLayout;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)reset;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setAddStatesFromChildrenWithBoolean:(jboolean)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setAlphaWithFloat:(jfloat)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setAsDragSourceWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setAttributeUnderTestWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setBackgroundRepeatWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setBackgroundTintModeWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setBackgroundTintWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setBackgroundWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setChildXmlWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setClickableWithBoolean:(jboolean)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setClipChildrenWithBoolean:(jboolean)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setClipToPaddingWithBoolean:(jboolean)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setContentDescriptionWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setCustomErrorMessageKeysWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setCustomErrorMessageValuesWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setDuplicateParentStateWithBoolean:(jboolean)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setElevationWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setEnabledWithBoolean:(jboolean)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setErrorStyleWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setFocusableWithBoolean:(jboolean)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setForegroundGravityWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setForegroundRepeatWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setForegroundTintModeWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setForegroundTintWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setForegroundWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setIdWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setInvalidateOnFrameChangeWithBoolean:(jboolean)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setIosAccessibilityHintWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setIosAccessibilityIgnoresInvertColorsWithBoolean:(jboolean)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setIosAccessibilityLabelWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setIosAccessibilityTraitsWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setIosAccessibilityValueWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setIosAlphaWithFloat:(jfloat)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setIosAutoresizesSubviewsWithBoolean:(jboolean)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setIosBackgroundColorWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setIosClearsContextBeforeDrawingWithBoolean:(jboolean)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setIosClipsToBoundsWithBoolean:(jboolean)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setIosContentScaleFactorWithFloat:(jfloat)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setIosInsetsLayoutMarginsFromSafeAreaWithBoolean:(jboolean)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setIosIsAccessibilityElementWithBoolean:(jboolean)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setIosIsExclusiveTouchWithBoolean:(jboolean)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setIosIsHiddenWithBoolean:(jboolean)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setIosIsMultipleTouchEnabledWithBoolean:(jboolean)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setIosIsOpaqueWithBoolean:(jboolean)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setIosIsUserInteractionEnabledWithBoolean:(jboolean)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setIosLargeContentImageWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setIosLargeContentTitleWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setIosLayerBorderColorWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setIosLayerBorderWidthWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setIosLayerCornerRadiusWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setIosLayerMasksToBoundsWithBoolean:(jboolean)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setIosPreservesSuperviewLayoutMarginsWithBoolean:(jboolean)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setIosRestorationIdentifierWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setIosScalesLargeContentImageWithBoolean:(jboolean)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setIosShowsLargeContentViewerWithBoolean:(jboolean)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setIosTagWithInt:(jint)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setIosTintColorWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setIosTranslatesAutoresizingMaskIntoConstraintsWithBoolean:(jboolean)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setKeepScreenOnWithBoolean:(jboolean)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setLayoutDirectionWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setLayoutModeWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setListitemWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setLongClickableWithBoolean:(jboolean)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setMaxHeightWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setMaxWidthWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setMinHeightWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setMinWidthWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setModelDescPathWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setModelForWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setModelIdPathWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setModelParamWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setModelPojoToUiParamsWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setModelPojoToUiWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setModelSyncEventsWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setModelUiToPojoEventIdsWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setModelUiToPojoWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setOnAnimationCancelWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setOnAnimationEndWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setOnAnimationRepeatWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setOnAnimationStartWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setOnChildViewAddedWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setOnChildViewRemovedWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setOnClickWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setOnDragWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setOnKeyWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setOnLongClickWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setOnSwipedWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setOnTouchWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setOutsideTouchableWithBoolean:(jboolean)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setPaddingBottomWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setPaddingEndWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setPaddingHorizontalWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setPaddingLeftWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setPaddingRightWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setPaddingStartWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setPaddingTopWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setPaddingVerticalWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setPaddingWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setRotationWithFloat:(jfloat)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setRotationXWithFloat:(jfloat)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setRotationYWithFloat:(jfloat)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setScaleXWithFloat:(jfloat)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setScaleYWithFloat:(jfloat)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setSelectedWithBoolean:(jboolean)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setStyleWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setTextAlignmentWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setTextDirectionWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setTransformPivotXWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setTransformPivotYWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setTranslationXWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setTranslationYWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setTranslationZWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setV_maxlengthWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setV_maxWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setV_minlengthWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setV_minWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setV_patternWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setV_requiredWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setV_typeWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setValidationErrorDisplayTypeWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setValidationWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setVisibilityWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)setZIndexWithInt:(jint)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)startAnimator;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetAddStatesFromChildren;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetAlpha;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetBackground;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetBackgroundTint;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetBackgroundTintMode;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetClickable;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetClipChildren;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetClipToPadding;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetContentDescription;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetDuplicateParentState;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetEnabled;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetFocusable;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetForeground;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetForegroundGravity;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetForegroundTint;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetForegroundTintMode;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetId;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetIosAccessibilityHint;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetIosAccessibilityIgnoresInvertColors;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetIosAccessibilityLabel;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetIosAccessibilityTraits;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetIosAccessibilityValue;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetIosAlpha;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetIosAutoresizesSubviews;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetIosBackgroundColor;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetIosClearsContextBeforeDrawing;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetIosClipsToBounds;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetIosContentScaleFactor;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetIosInsetsLayoutMarginsFromSafeArea;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetIosIsAccessibilityElement;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetIosIsExclusiveTouch;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetIosIsFocused;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetIosIsHidden;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetIosIsMultipleTouchEnabled;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetIosIsOpaque;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetIosIsUserInteractionEnabled;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetIosLargeContentImage;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetIosLargeContentTitle;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetIosPreservesSuperviewLayoutMargins;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetIosRestorationIdentifier;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetIosScalesLargeContentImage;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetIosShowsLargeContentViewer;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetIosTag;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetIosTintColor;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetIosTranslatesAutoresizingMaskIntoConstraints;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetKeepScreenOn;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetLayoutDirection;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetLayoutMode;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetLongClickable;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetMaxHeight;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetMaxWidth;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetMinHeight;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetMinWidth;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetModelDescPath;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetModelIdPath;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetModelParam;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetModelPojoToUi;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetModelSyncEvents;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetModelUiToPojo;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetPaddingBottom;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetPaddingEnd;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetPaddingLeft;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetPaddingRight;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetPaddingStart;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetPaddingTop;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetRotation;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetRotationX;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetRotationY;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetScaleX;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetScaleY;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetSelected;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetTextAlignment;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetTextDirection;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetTransformPivotX;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetTransformPivotY;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetTranslationX;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetTranslationY;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetTranslationZ;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetValidateForm;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)tryGetVisibility;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)updateModelDataWithNSString:(NSString *)arg0
                                                                                          withId:(id)arg1;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *)validateFormWithNSString:(NSString *)arg0;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder)

FOUNDATION_EXPORT void ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder_initWithASSnackbarContentLayoutImpl_(ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *self, ASSnackbarContentLayoutImpl *outer$);

FOUNDATION_EXPORT ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *new_ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder_initWithASSnackbarContentLayoutImpl_(ASSnackbarContentLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder *create_ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder_initWithASSnackbarContentLayoutImpl_(ASSnackbarContentLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandBuilder)

#endif

#if !defined (ASSnackbarContentLayoutImpl_SnackbarContentLayoutBean_) && (INCLUDE_ALL_SnackbarContentLayoutImpl || defined(INCLUDE_ASSnackbarContentLayoutImpl_SnackbarContentLayoutBean))
#define ASSnackbarContentLayoutImpl_SnackbarContentLayoutBean_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupBean 1
#include "ViewGroupImpl.h"

@class ASSnackbarContentLayoutImpl;
@protocol ASIWidget;

@interface ASSnackbarContentLayoutImpl_SnackbarContentLayoutBean : ASViewGroupImpl_ViewGroupBean

#pragma mark Public

- (instancetype)initWithASSnackbarContentLayoutImpl:(ASSnackbarContentLayoutImpl *)outer$;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithASIWidget:(id<ASIWidget>)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASSnackbarContentLayoutImpl_SnackbarContentLayoutBean)

FOUNDATION_EXPORT void ASSnackbarContentLayoutImpl_SnackbarContentLayoutBean_initWithASSnackbarContentLayoutImpl_(ASSnackbarContentLayoutImpl_SnackbarContentLayoutBean *self, ASSnackbarContentLayoutImpl *outer$);

FOUNDATION_EXPORT ASSnackbarContentLayoutImpl_SnackbarContentLayoutBean *new_ASSnackbarContentLayoutImpl_SnackbarContentLayoutBean_initWithASSnackbarContentLayoutImpl_(ASSnackbarContentLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSnackbarContentLayoutImpl_SnackbarContentLayoutBean *create_ASSnackbarContentLayoutImpl_SnackbarContentLayoutBean_initWithASSnackbarContentLayoutImpl_(ASSnackbarContentLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASSnackbarContentLayoutImpl_SnackbarContentLayoutBean)

#endif

#if !defined (ASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean_) && (INCLUDE_ALL_SnackbarContentLayoutImpl || defined(INCLUDE_ASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean))
#define ASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupParamsBean 1
#include "ViewGroupImpl.h"

@class ASSnackbarContentLayoutImpl;
@protocol ASIWidget;

@interface ASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean : ASViewGroupImpl_ViewGroupParamsBean

#pragma mark Public

- (instancetype)initWithASSnackbarContentLayoutImpl:(ASSnackbarContentLayoutImpl *)outer$;

- (id)getLayoutGravityWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutWeightWithASIWidget:(id<ASIWidget>)w;

- (void)setLayoutGravityWithASIWidget:(id<ASIWidget>)w
                         withNSString:(NSString *)value;

- (void)setLayoutWeightWithASIWidget:(id<ASIWidget>)w
                           withFloat:(jfloat)value;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean)

FOUNDATION_EXPORT void ASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean_initWithASSnackbarContentLayoutImpl_(ASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean *self, ASSnackbarContentLayoutImpl *outer$);

FOUNDATION_EXPORT ASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean *new_ASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean_initWithASSnackbarContentLayoutImpl_(ASSnackbarContentLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean *create_ASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean_initWithASSnackbarContentLayoutImpl_(ASSnackbarContentLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASSnackbarContentLayoutImpl_SnackbarContentLayoutParamsBean)

#endif

#if !defined (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder_) && (INCLUDE_ALL_SnackbarContentLayoutImpl || defined(INCLUDE_ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder))
#define ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupCommandParamsBuilder 1
#include "ViewGroupImpl.h"

@class ASSnackbarContentLayoutImpl;

@interface ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder : ASViewGroupImpl_ViewGroupCommandParamsBuilder

#pragma mark Public

- (instancetype)initWithASSnackbarContentLayoutImpl:(ASSnackbarContentLayoutImpl *)outer$;

- (id)getLayoutGravity;

- (id)getLayoutWeight;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *)reset;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *)setLayoutGravityWithNSString:(NSString *)value;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *)setLayoutMarginBottomWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *)setLayoutMarginEndWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *)setLayoutMarginHorizontalWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *)setLayoutMarginLeftWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *)setLayoutMarginRightWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *)setLayoutMarginStartWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *)setLayoutMarginTopWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *)setLayoutMarginVerticalWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *)setLayoutMarginWithNSString:(NSString *)arg0;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *)setLayoutWeightWithFloat:(jfloat)value;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *)tryGetLayoutGravity;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *)tryGetLayoutMarginBottom;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *)tryGetLayoutMarginEnd;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *)tryGetLayoutMarginLeft;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *)tryGetLayoutMarginRight;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *)tryGetLayoutMarginStart;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *)tryGetLayoutMarginTop;

- (ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *)tryGetLayoutWeight;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder)

FOUNDATION_EXPORT void ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder_initWithASSnackbarContentLayoutImpl_(ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *self, ASSnackbarContentLayoutImpl *outer$);

FOUNDATION_EXPORT ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *new_ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder_initWithASSnackbarContentLayoutImpl_(ASSnackbarContentLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder *create_ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder_initWithASSnackbarContentLayoutImpl_(ASSnackbarContentLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASSnackbarContentLayoutImpl_SnackbarContentLayoutCommandParamsBuilder)

#endif

#pragma pop_macro("INCLUDE_ALL_SnackbarContentLayoutImpl")
