//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSSnackbarPlugin\src\main\java\com\ashera\snackbar\SnackbarLayoutImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_SnackbarLayoutImpl")
#ifdef RESTRICT_SnackbarLayoutImpl
#define INCLUDE_ALL_SnackbarLayoutImpl 0
#else
#define INCLUDE_ALL_SnackbarLayoutImpl 1
#endif
#undef RESTRICT_SnackbarLayoutImpl

#if !defined (ASSnackbarLayoutImpl_) && (INCLUDE_ALL_SnackbarLayoutImpl || defined(INCLUDE_ASSnackbarLayoutImpl))
#define ASSnackbarLayoutImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASWidgetAttribute;
@class IOSClass;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASSnackbarLayoutImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (IOSClass *)getViewClass;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (jboolean)removeWithInt:(jint)index;

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASSnackbarLayoutImpl)

inline NSString *ASSnackbarLayoutImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASSnackbarLayoutImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASSnackbarLayoutImpl, LOCAL_NAME, NSString *)

inline NSString *ASSnackbarLayoutImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASSnackbarLayoutImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASSnackbarLayoutImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASSnackbarLayoutImpl_init(ASSnackbarLayoutImpl *self);

FOUNDATION_EXPORT ASSnackbarLayoutImpl *new_ASSnackbarLayoutImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSnackbarLayoutImpl *create_ASSnackbarLayoutImpl_init(void);

FOUNDATION_EXPORT void ASSnackbarLayoutImpl_initWithNSString_(ASSnackbarLayoutImpl *self, NSString *localname);

FOUNDATION_EXPORT ASSnackbarLayoutImpl *new_ASSnackbarLayoutImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSnackbarLayoutImpl *create_ASSnackbarLayoutImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASSnackbarLayoutImpl_initWithNSString_withNSString_(ASSnackbarLayoutImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASSnackbarLayoutImpl *new_ASSnackbarLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSnackbarLayoutImpl *create_ASSnackbarLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASSnackbarLayoutImpl)

@compatibility_alias ComAsheraSnackbarSnackbarLayoutImpl ASSnackbarLayoutImpl;

#endif

#if !defined (ASSnackbarLayoutImpl_SnackbarLayoutExt_) && (INCLUDE_ALL_SnackbarLayoutImpl || defined(INCLUDE_ASSnackbarLayoutImpl_SnackbarLayoutExt))
#define ASSnackbarLayoutImpl_SnackbarLayoutExt_

#define RESTRICT_Snackbar 1
#define INCLUDE_ADXSnackbar_SnackbarLayout 1
#include "Snackbar.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASSnackbarLayoutImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASSnackbarLayoutImpl_SnackbarLayoutExt : ADXSnackbar_SnackbarLayout < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASSnackbarLayoutImpl:(ASSnackbarLayoutImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (jint)getMaxHeight;

- (jint)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(jint)height;

- (void)setMaxWidthWithInt:(jint)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASSnackbarLayoutImpl_SnackbarLayoutExt)

FOUNDATION_EXPORT void ASSnackbarLayoutImpl_SnackbarLayoutExt_initWithASSnackbarLayoutImpl_(ASSnackbarLayoutImpl_SnackbarLayoutExt *self, ASSnackbarLayoutImpl *outer$);

FOUNDATION_EXPORT ASSnackbarLayoutImpl_SnackbarLayoutExt *new_ASSnackbarLayoutImpl_SnackbarLayoutExt_initWithASSnackbarLayoutImpl_(ASSnackbarLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSnackbarLayoutImpl_SnackbarLayoutExt *create_ASSnackbarLayoutImpl_SnackbarLayoutExt_initWithASSnackbarLayoutImpl_(ASSnackbarLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASSnackbarLayoutImpl_SnackbarLayoutExt)

#endif

#pragma pop_macro("INCLUDE_ALL_SnackbarLayoutImpl")
