//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSSnackbarPlugin\src\main\java\com\ashera\snackbar\SnackbarPlugin.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_SnackbarPlugin")
#ifdef RESTRICT_SnackbarPlugin
#define INCLUDE_ALL_SnackbarPlugin 0
#else
#define INCLUDE_ALL_SnackbarPlugin 1
#endif
#undef RESTRICT_SnackbarPlugin

#if !defined (ASSnackbarPlugin_) && (INCLUDE_ALL_SnackbarPlugin || defined(INCLUDE_ASSnackbarPlugin))
#define ASSnackbarPlugin_

@interface ASSnackbarPlugin : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)initPlugin OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASSnackbarPlugin)

FOUNDATION_EXPORT void ASSnackbarPlugin_init(ASSnackbarPlugin *self);

FOUNDATION_EXPORT ASSnackbarPlugin *new_ASSnackbarPlugin_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSnackbarPlugin *create_ASSnackbarPlugin_init(void);

FOUNDATION_EXPORT void ASSnackbarPlugin_initPlugin(void);

J2OBJC_TYPE_LITERAL_HEADER(ASSnackbarPlugin)

@compatibility_alias ComAsheraSnackbarSnackbarPlugin ASSnackbarPlugin;


#endif

#pragma pop_macro("INCLUDE_ALL_SnackbarPlugin")
